# Generated by Django 3.2.11 on 2022-05-19 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='firstname',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='lastname',
            new_name='Lastname',
        ),
    ]
