# Generated by Django 3.2.11 on 2022-05-22 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220519_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
