# Generated by Django 3.2.11 on 2022-05-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_patient_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Date',
            field=models.DateField(),
        ),
    ]
